Version 2 authentication
mihaitzzza/nt-team2-tic-tac-toe pull request #3
Opened 2021-02-16 16:35 UTC by ciurezbogdan

2021-02-21 17:00 UTC, mihaitzzza requested changes

2021-02-21 17:00 UTC, mihaitzzza commented on game/__init__.py
> +#  returns tuple with player_1 and player_2 first_name
What's up with this comment? Seems unneeded to me.

2021-02-21 17:00 UTC, mihaitzzza commented on game/__init__.py
> +            player_name, sign = get_current_player(step, players[0], players[1])
Why would you pass the players as individual data instead of the whole `players` variable?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +import json
To much functionality in `__init__.py` module. I don't see the reason to have an `access` package instead of an `access.py` module. Do I miss something?
Also, are you sure this functionality of register is part of the Tic-Tac-Toe game? Does it influence somehow the functionality of the game itself? I don't think so.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +def hash_password(p):
Who's `p`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    m = hashlib.sha1()
Who's `m`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    pas = str(p).encode('utf-8')
Who's `pas`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +def str_chk(user):
Is the `user` variable actually an object? I don't think so.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    b = re.match('^(?=.*[a-z])(?=.*[0-9])[a-z,0-9]{6,}$', user)
Who's `b`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        c = b.group(0)
What? So you're doing a `while` just to break it so you can have an `else` branch? :-o
```
if b is not None:
   return b.group(0)
return b
```

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    first_name = input('First_name: ')
What if I hit enter without typing something for `first_name` and `last_name`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        user_name = user_name.strip()
Duplicates lines 44 & 45. Rethink it so you won't have to do that.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        user_name = str_chk(user_name)
Is it already good or you shall check if it's good? Also, please check what happens if I insert only `0` as username.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    email_address = input('Email_address: ')
What if I won't type anything?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        password = password.strip()
Duplicates lines 63&64. Please refactor this so you won't have to duplicate code.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        password_confirmation = hash_password(password_confirmation.strip())
Duplicates lines 75-78. Please refactor so you won't have to duplicate the code.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +def loggin():
`login` not `loggin`.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    user = input('username: ')
Please use `username` since that's what the variable actually represents.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        pasw = getpass.getpass('password: ')
No way `pasw`. You should either you `pass` or `password`. I suggest the long name for now.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                else:
Do you need this `else` since you're doing a return on L123?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                            return loggin()
Why would this function be recursive? It uses NOTHING from previous call. You recheck if the file exists and reopen it if it exists EVERYTIME the use inputs a wrong password - do you think that's OK performance wise?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +            elif sel != 1:
If `sel` is not equal to `'1'` it means it will be different then `'1'`. So the `elif` should not exists. It should be an `else` branch. On the other hand, since `sel` is read from keyboard, IT WILL ALWAYS BE `!=` (different) then `1` because it's a string, not a number.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +    if 'data' not in os.listdir('game'):
Please move this check somewhere else to be made only once per app run, not on every register step.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        print("""\nPlease select option:
This code duplicates the code from the `if` branch. It's 90% the same, expect you're doing it for different players (either for Player 2 or for Player 1). Please refactor to NOT have duplicate code.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +            print('Player 2')
Haven't you already done this twice on the previous lines?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +def chg_pass(user):
Please stop using abbreviations.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +        try:
Don't you do an `if` on Line 205? Why do you have to use the `try...except`? I think this also applies to previous code.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                        print('pass is good')
On line 214 you're doing `if hash_password(pasw) == credentials_f['password']:` ... on this `else` you're saying `'pass is good'`....is it good for the password to mismatch? :-o

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                            new_pasw = new_pasw.strip()
This duplicates lines 220 & 221.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                                new_pasw = getpass.getpass('Type new password: ')
This duplicates lines 220 & 221.

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                    password_confirmation = getpass.getpass('Confirm new_password: ')
This duplicates lines inside the `if`. Why are you doing them both inside the `if` and outside the `if`?

2021-02-21 17:00 UTC, mihaitzzza commented on game/access/__init__.py
> +                            new_pasw = new_pasw.strip()
This duplicates lines 244 & 245

2021-02-21 17:00 UTC, mihaitzzza commented on game/data/_admin/_admin.json
> +{"first_name": "admin", "last_name": "admin", "user_name": "_admin", "email_address": "a@b.com", "password": "d033e22ae348aeb5660fc2140aec35850c4da997"}
Why are you creating an `_admin`, `_admin2`, `_admin3` folder? If the reason for this is because you're creating a FOLDER for each user, that's bad. You should have a FILE for each user, not a FOLDER. Also, please add them to `.gitignore`, anyone will have to create OWN users. I don't want to use yours as much as you don't want to use mines.

2021-02-21 17:00 UTC, mihaitzzza commented on game/player.py
> +        name = pl1
If you're sending the whole tuple of `players` you will be easier get the current one's name :)

2021-02-21 17:00 UTC, mihaitzzza commented on main.py
> +
Please get rid of these empty lines.

2021-02-21 17:00 UTC, mihaitzzza commented on main.py
> +            exit(0)
Please use `sys.exit(0)` instead of `exit(0)`
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python

2021-02-22 08:27 UTC, ciurezbogdan commented on main.py
> +            exit(0)
I didn't know about sys.exit(0), however I have studied the link and it is clear your point of view

2021-02-22 08:32 UTC, ciurezbogdan commented on main.py
> +
You are right there is no reason for them

2021-02-22 09:25 UTC, ciurezbogdan commented on game/player.py
> +        name = pl1
I have rewrite the function for tuple players

2021-02-22 09:27 UTC, ciurezbogdan commented on game/player.py
> +        name = pl1
and reconfigure as well game\__init__.py

2021-02-22 09:32 UTC, ciurezbogdan commented on game/data/_admin/_admin.json
> +{"first_name": "admin", "last_name": "admin", "user_name": "_admin", "email_address": "a@b.com", "password": "d033e22ae348aeb5660fc2140aec35850c4da997"}
As we discussed before the idea was that each player will have a folder containing credentials and logg files as well.
I still don't know who is in charge for logging in our team. However I can easily drop the folder creation and keep just credential files.
Folders are created by me just for test purpose.

2021-02-22 09:36 UTC, ciurezbogdan commented on game/access/__init__.py
> +                            new_pasw = new_pasw.strip()
I will remove them

2021-02-22 10:09 UTC, mihaitzzza commented on game/data/_admin/_admin.json
> +{"first_name": "admin", "last_name": "admin", "user_name": "_admin", "email_address": "a@b.com", "password": "d033e22ae348aeb5660fc2140aec35850c4da997"}
I rather prefer something like `data/users/gigel.json` and here we can have something like:
```
{
   "first_name": <first_name>,
   "last_name": <last_name>,
   "email": <email>,
   "password": <hashed_password>,
   "stats": {}
}
```
And each user will have it's own `username.json` file within `data/users` folder.

2021-02-22 10:58 UTC, ciurezbogdan commented on game/access/__init__.py
> +            print('Player 2')
Here is my logic:
I have 2 cases each one with 2 other cases:
player1 login
case 1: player1 not none > player2 login >player 2 is not none > return pleyer1 and player2
                                                               or  player2 is none > register > login > return player1 and 2
case2: player1 is none > register > login  > player2 login > player 2 is not none > return pleyer1 and player2
                                                                                          or  player2 is none > register > login > return player1 and 2
And of course I must give the option to register or exit in case of misspell.

2021-02-22 10:59 UTC, ciurezbogdan commented on game/access/__init__.py
> +def chg_pass(user):
Got it

2021-02-22 11:02 UTC, mihaitzzza commented on game/access/__init__.py
> +            print('Player 2')
I understand, but the menu for register or exit, checking the selection etc. is duplicated. You should get rid (somehow :smile:) of the duplicates. The easiest way is to wrap the code into a function. That's the first step I would do here. After that, we can have another look if it's possible to lower the function calls and rethink how the cases should be covered.

2021-02-22 11:36 UTC, ciurezbogdan commented on game/access/__init__.py
> +    if 'data' not in os.listdir('game'):
Does this check better be included in game/__init__.py in start() function?
This will be my next option for checking data folder.

2021-02-22 11:36 UTC, ciurezbogdan commented on game/access/__init__.py
> +            elif sel != 1:
Got it

2021-02-22 11:37 UTC, mihaitzzza commented on game/access/__init__.py
> +    if 'data' not in os.listdir('game'):
I would suggest `main`. It's what the system need in order to be able to run OK.

2021-02-22 11:39 UTC, ciurezbogdan commented on game/access/__init__.py
> +    if 'data' not in os.listdir('game'):
Ok. Thank you.

2021-02-22 15:04 UTC, ciurezbogdan commented on game/access/__init__.py
> +                            return loggin()
OK, then for wrong password input I will just get back to main menu.

2021-02-22 15:09 UTC, ciurezbogdan commented on game/access/__init__.py
> +                else:
I need to inform user that his input password is wrong.

2021-02-22 15:10 UTC, ciurezbogdan commented on game/access/__init__.py
> +        pasw = getpass.getpass('password: ')
Got it

2021-02-23 07:55 UTC, mihaitzzza commented on game/access/__init__.py
> +                else:
I agree, but since you're doing `return` on L123 (inside the `if`), you can write the code directly, without using the `else` branch. If the condition will be met, the `if` branch is ran and the `return` will exit the function. Therefore any code below the `if` won't be executed.
It's nothing wrong in keeping the `else`, but it's cleaner to just write the code without having an `else` branch.

2021-02-23 08:25 UTC, ciurezbogdan commented on game/access/__init__.py
> +                else:
I think I understand. So , the 'Wrong password message' will be at the same level with the 'if' instruction not on the else branch.

2021-02-23 08:26 UTC, ciurezbogdan commented on game/access/__init__.py
> +    user = input('username: ')
Clear

2021-02-23 08:27 UTC, ciurezbogdan commented on game/access/__init__.py
> +def loggin():
Clear

2021-02-23 08:28 UTC, ciurezbogdan commented on game/access/__init__.py
> +    email_address = input('Email_address: ')
I will add regex conditions to limit the input options.

2021-02-23 08:28 UTC, ciurezbogdan commented on game/access/__init__.py
> +        user_name = str_chk(user_name)
Clear

2021-02-23 08:29 UTC, ciurezbogdan commented on game/access/__init__.py
> +    first_name = input('First_name: ')
I will add regex conditions to limit input options

2021-02-23 08:29 UTC, ciurezbogdan commented on game/access/__init__.py
> +        c = b.group(0)
Got it

2021-02-23 08:46 UTC, mihaitzzza commented on game/access/__init__.py
> +                else:
Correct!

2021-02-23 10:03 UTC, ciurezbogdan commented on game/__init__.py
> +            player_name, sign = get_current_player(step, players[0], players[1])
Got it

2021-02-23 10:13 UTC, ciurezbogdan commented on game/__init__.py
> +#  returns tuple with player_1 and player_2 first_name
Done

2021-02-23 10:17 UTC, ciurezbogdan commented on game/access/__init__.py
> +def hash_password(p):
renamed  'word'

2021-02-23 10:17 UTC, ciurezbogdan commented on game/access/__init__.py
> +    m = hashlib.sha1()
renamed 'hash_tool'

2021-02-23 10:19 UTC, ciurezbogdan commented on game/access/__init__.py
> +    pas = str(p).encode('utf-8')
renamed 'encode_pass'

2021-02-23 10:22 UTC, ciurezbogdan commented on game/access/__init__.py
> +    b = re.match('^(?=.*[a-z])(?=.*[0-9])[a-z,0-9]{6,}$', user)
renamed 'result'

2021-02-23 10:24 UTC, ciurezbogdan commented on game/access/__init__.py
> +        pasw = getpass.getpass('password: ')
renamed 'password'

2021-02-23 11:02 UTC, ciurezbogdan commented on game/access/__init__.py
> +def str_chk(user):
rename it to word and define it as string type

2021-02-24 08:57 UTC, ciurezbogdan commented on game/access/__init__.py
> +            print('Player 2')
I have created a register_menu function and used while instead of if

2021-02-24 12:10 UTC, ciurezbogdan commented on game/access/__init__.py
> +        print("""\nPlease select option:
new aproach

2021-02-28 15:27 UTC, mihaitzzza requested changes

2021-02-28 15:27 UTC, mihaitzzza commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
`f'{username}.json'` is used multiple times. Please just do `username_file = f'{username}.json'` once and reuse the variabile. This way you're code will rely on the variable's value instead of the string itself.
Also you're using multiple times `os.path.join('data', 'users')`. This is also not quite OK because you'll have to check all the occurrences and replace them if you'll have to change to path.

2021-02-28 15:27 UTC, mihaitzzza commented on access/__init__.py
> +
Unneeded empty line.

2021-02-28 15:27 UTC, mihaitzzza commented on access/__init__.py
> +
Unneeded empty line.

2021-02-28 15:27 UTC, mihaitzzza commented on access/__init__.py
> +    player_1 = login()
What happens if the the login is wrong because I mistyped my password? I don't see a way to login anymore.

2021-02-28 15:27 UTC, mihaitzzza commented on access/__init__.py
> +
Unneeded empty line.

2021-02-28 15:27 UTC, mihaitzzza commented on access/check_engine.py
> +    else:
Unneeded `else` branch.

2021-02-28 15:27 UTC, mihaitzzza commented on access/check_engine.py
> +    else:
Unneeded `else` branch.

2021-02-28 15:27 UTC, mihaitzzza commented on access/check_engine.py
> +    else:
Unneded `else` branch.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        first_name = input('First_name: ')
Please stop duplicating code outside and inside `while` loops. This duplicates L28.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        last_name = input('Last_name: ')
Please stop duplicating code outside and inside `while` loops. This duplicates L34.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        user_name = user_name.strip()
Please stop duplicating code outside and inside `while` loops. This duplicates lines L41-L42.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        email_address = input('Email_address: ')
Please stop duplicating code outside and inside `while` loops. This duplicates L55.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        password_confirmation = password_confirmation.strip()
Please stop duplicating code outside and inside `while` loops. This duplicates lines L62-L66.

2021-02-28 15:27 UTC, mihaitzzza commented on access/register_engine.py
> +        password_confirmation = hash_password(password_confirmation.strip())
Same here. You're using these 4 lines 3 times in about 20 lines of code.

2021-02-28 15:27 UTC, mihaitzzza commented on game/player.py
> +def get_current_player(step, players=()):
Default value is not needed. You're using `[0]` and `[1]` on L10 and L12. It's obvious the `players` cannot be `()` (empty tuple).

2021-03-01 09:42 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Done. I used username_file and user_path var instead.

2021-03-01 09:42 UTC, ciurezbogdan commented on access/__init__.py
> +
Done

2021-03-01 09:42 UTC, ciurezbogdan commented on access/__init__.py
> +
Done

2021-03-01 09:43 UTC, ciurezbogdan commented on access/__init__.py
> +
Done

2021-03-01 10:29 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
I come back to this subject: if I use a variable for path the returned value is 'data\\users' instead of 'data\users' and I can not figure it out.

2021-03-01 10:30 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Sorry returned value is 'data\\users'

2021-03-01 10:31 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Here I cannot write it, actually is double back slash

2021-03-01 10:47 UTC, mihaitzzza commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Are you saying the following code doesn't work?
```
data_folder_path = os.path.join('data', 'users')
username_file = os.path.join(data_folder_path, f'{username}.json')
```

2021-03-01 11:36 UTC, ciurezbogdan commented on access/check_engine.py
> +    else:
Done

2021-03-01 11:37 UTC, ciurezbogdan commented on access/check_engine.py
> +    else:
Done

2021-03-01 11:37 UTC, ciurezbogdan commented on access/check_engine.py
> +    else:
Done

2021-03-01 11:45 UTC, ciurezbogdan commented on access/register_engine.py
> +        first_name = input('First_name: ')
It is not clear for me how it works.
Can you show me how to rewrite the code above?

2021-03-01 11:55 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Now is clear. I have made a wrong definition of username var

2021-03-01 11:56 UTC, mihaitzzza commented on access/register_engine.py
> +        first_name = input('First_name: ')
```
first_name = ''
while not character_check(first_name):
     ...
```
In this way you won't do the keyboard reading twice. Think about if you're suppose to update the code and you'll have to get the `first_name` from someone else.

2021-03-01 11:57 UTC, ciurezbogdan commented on access/register_engine.py
> +        user_name = user_name.strip()
It is not clear for me how it works.
Can you , please, show me how to rewrite.

2021-03-01 12:28 UTC, ciurezbogdan commented on access/register_engine.py
> +        first_name = input('First_name: ')
So the only difference is to check : not None instead of : is None?
But still I need a new value for first_name in case character_check returns None and this will be inside the while loop, wright?

2021-03-01 12:32 UTC, mihaitzzza commented on access/register_engine.py
> +        first_name = input('First_name: ')
You read `first_name` only inside the `while` loop, not both inside and outside. Outside the loop you're just assigning a default value. That's the main difference. The `while` condition is just a shorter (and easier) way to check against `None`. If `character_check` returns `None`, the `while` loop is executed so you'll have to read the `first_name` value on the first line inside the `while`.

2021-03-01 12:59 UTC, ciurezbogdan commented on access/register_engine.py
> +        first_name = input('First_name: ')
Now I get it. Outside while I just create first_name variable which is empty and the reading (including first reading) is inside the loop, wright?

2021-03-01 13:09 UTC, ciurezbogdan commented on access/register_engine.py
> +        first_name = input('First_name: ')
would this be a reasonable solution?
first_name = ''
    while not character_check(first_name):
        first_name = input('First_name: ')
        first_name = first_name.strip()
        if character_check(first_name) is None:
            print('Characters not permitted')

2021-03-01 13:33 UTC, mihaitzzza commented on access/register_engine.py
> +        first_name = input('First_name: ')
If that's your use case, then you have to adapt the code. the `character_check` is done twice ... why?
```
first_name = None
while not first_name:
     first_name = input('First name:')
     first_name = first_name.strip()

     if not character_check(first_name):
          print('Characters not permitted.')
          first_name = None
```
Also that `character_check` is not suggestive. I would name it `validate_name`.

2021-03-01 15:02 UTC, ciurezbogdan commented on access/register_engine.py
> +        first_name = input('First_name: ')
Thank you

2021-03-02 10:50 UTC, ciurezbogdan commented on access/__init__.py
> +    if f'{username}.json' in os.listdir(os.path.join('data', 'users')):
Done

2021-03-02 10:52 UTC, ciurezbogdan commented on access/__init__.py
> +    player_1 = login()
I have modified login() and is prompting for retype password

2021-03-02 10:53 UTC, ciurezbogdan commented on access/register_engine.py
> +        password_confirmation = hash_password(password_confirmation.strip())
Done

2021-03-02 10:54 UTC, ciurezbogdan commented on access/register_engine.py
> +        last_name = input('Last_name: ')
Done

2021-03-02 10:55 UTC, ciurezbogdan commented on access/register_engine.py
> +        user_name = user_name.strip()
Now is clear.
Done

2021-03-02 10:55 UTC, ciurezbogdan commented on access/register_engine.py
> +        email_address = input('Email_address: ')
Done

2021-03-02 10:55 UTC, ciurezbogdan commented on access/register_engine.py
> +        password_confirmation = password_confirmation.strip()
Done

2021-03-03 09:20 UTC, mihaitzzza requested changes

2021-03-03 09:20 UTC, mihaitzzza commented on access/__init__.py
> +                        credentials_f['password'] = hash_password(new_pass)
I don't like this at all. It's way to complex and you still do reading twice. First of all I would create the following function. This function can be called whenever you'll need to get `users_data` from file:
```
def get_user_data(username: str):
     try:
          with open(username_file_path) as json_file:
               user_data = json.load(json_file)
     except IOError:
          print("Warning: auth file not found")

     return user_data
```
After I would refactor the `change_pass` function as follows:
```
def change_password(username: str):
     user_data = get_user_data(username)
     
     if user_data:
          password = None
          iterations = 0
          while iterations < 3:
               print('you have %s remaining tries' % 3 - iterations)
               password = input('password:')
               hashed_password = hash_password(password)
               
               if hashed_password == user_data['password']:
                    break

               password = None
               iterations += 1
          if password:
               new_password = None
               while not new_password:
                    new_password = input('new password: ')
                    new_password_confirmation = input('confirm new password: ')
                    if new_password != new_password_confirmation:
                         print('password not confirmed. Please try again')
                         new_password = None
                         continue
                   if new_password == password:
                        new_password = None
              ... do writing to file and print a password correctly changed or whatever.
```

2021-03-03 09:20 UTC, mihaitzzza commented on main.py
> +import os
Unused import? Please remove it if so.

2021-03-03 09:20 UTC, mihaitzzza commented on main.py
> +
Why are you touching files you don't have to?

2021-03-03 09:20 UTC, mihaitzzza commented on game/player.py
>          return players[1], 'o'
Doesn't PyCharm warn for empty line at the end of a file?

2021-03-03 09:20 UTC, mihaitzzza commented on access/__init__.py
>      print('login now')
Please move all the functions inside `access/__init__.py` to another module (I suppose `auth.py`) inside the `access` package. Those are not functions needed for configuring the `access` package or "an entry point" of the package, therefore their place isn't in `__init__.py` file.

2021-03-03 17:55 UTC, ciurezbogdan commented on access/__init__.py
> +    username_file = f'{user}.json'
I can declare user_path as global, however username_file depends on username and changes every time, it cannot be global.

2021-03-03 18:41 UTC, mihaitzzza commented on access/__init__.py
> +    username_file = f'{user}.json'
You're right. Please do.

2021-03-05 12:18 UTC, mihaitzzza requested changes
Seems to be just one more ;)) You're pretty close!

2021-03-05 12:18 UTC, mihaitzzza commented on access/auth.py
> +            iterations += 1
Isn't this code the same as the one from `login` function L30-L41? Move it to a `check_password` function that will return the `password` and do duplicate it.

2021-03-05 12:19 UTC, mihaitzzza commented on access/auth.py
> +        sys.exit(0)
I don't like the system exit here if for some reason I cannot log in. Maybe I'll want to register or try with another account. However, I won't block the PR for this.

2021-03-08 08:19 UTC, mihaitzzza requested changes

2021-03-08 08:19 UTC, mihaitzzza commented on access/auth.py
> +        menu_register()
I know you're too concentrated on solving this and I appreciate it. But that's the purpose of code review. To have another eye over your code from someone with "fresh eyes". You can refactor this to avoid code duplicate as follow:
```
def login_player(player_identifier):  # or something else to mark "Player 1" or "Player 2"
     player = None
     for counter in range(0, 2):
          print(player_identifier)
          player = login()
          counter += 1
          if player_1:
               break
     return player
```
and then you can use it as you've done:
```
player_1 = login_player('Player 1')
if not player_1:
     menu_register()
player_2 = login_player('Player 2')
if not player_2:
     menu_register()
```

2021-03-08 08:47 UTC, ciurezbogdan commented on access/auth.py
> +        menu_register()
Thank you for feedback. Actually your feedback and review is very important to me, it is the reason why I am participating to this course. I am working on avoiding code duplicating but still not there yet, so please be patient with me until I get it.

2021-03-12 11:57 UTC, mihaitzzza approved these changes

2021-03-13 08:12 UTC, merged